apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
spec:
  ports:
    - port: 3002
      targetPort: http
      protocol: TCP
      name: http
  type: LoadBalancer
  selector:
    app: rollouts-demo
